---
- name: Update Homebrew
  homebrew:
    name: git
    state: latest
    update_homebrew: true
  tags:
  - brew

- name: Cleanup Homebrew 
  command: brew cleanup
  
- name: Upgrade pyenv
  shell: brew unlink pyenv && brew install --head --fetch-head pyenv && brew link pyenv --head
  tags:
  - pyenv
