---
# TODO: make a play
brew install --cask --no-quarantine stretchly

When upgrading, run the following command.
Don't forget to Quit Stretchly, first.

brew update && brew upgrade --cask

# TODO update for Mac, below is linux
# TODO check permissions
- name: Ensure Stretchly config directory exists
  file:
    path: "/home/{{ ansible_user_id }}/.config/Stretchly"
    state: directory
    mode: '0755'

- name: Copy Stretchly configuration file
  copy:
    src: config.json
    dest: /home/{{ ansible_user_id }}/.config/Stretchly/config.json
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: '0644'
  become: yes

