---
#-------------- Collection: geerlingguy.mac --------------#
# homebrew: https://github.com/geerlingguy/ansible-collection-mac/tree/master/roles/homebrew
# casks
homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  # - Authy  # Doesn't seem to work anymore...
  - brave-browser
  - docker  # all inclusive of docker and docker desktop
  - dbeaver-community
  - discord
  - flux
  - logi-options-plus
  - microsoft-office
  - obsidian
  - orbstack
  - postman
  - slack
  - visual-studio-code
  - wezterm
  - whatsapp

# taps
homebrew_taps: []

# formulae
homebrew_installed_packages:
  # - ansible
  - dockutil  # Tool for managing Mac dock items
  - git
  # - go@1.20  # TODO install from website:https://go.dev/doc/install, https://go.dev/dl/
  - gh
  - grep
  - grpcurl
  - htop
  - jq
  - nvm
  - openssl@3
  - poetry
  - postgresql@16
  - pyenv
  - pyenv-virtualenv
  - rust
  # - solana  # See notes on 2024-08-06 as it was installed with sh command
  - tailscale  # TODO: test it isn't a cask # TODO: To start tailscale now and restart at login: brew services start tailscale
  - tree
  - wget
 
#-------------- Role: geerlingguy.dotfiles --------------#
# dock: https://github.com/geerlingguy/ansible-collection-mac/tree/master/roles/dock
configure_dock: true
dockitems_remove:
- Safari
- System Settings
- Messages
- Mail
- Maps
- Photos
- FaceTime
- Calendar
- Contacts
- Reminders
# - Notes 
- Freeform
- TV
- Music
- Keynote
- Numbers
- Pages
- App Store

dockitems_persist:
- name: "Authy"
  path: "/Applications/Authy Desktop.app/"
  pos: 5
- name: "Brave"
  path: "/Applications/Brave Browser.app/"
  pos: 4
- name: "DBeaver"
  path: "/Applications/DBeaver.app/"
  pos: 9
- name: "Discord"
  path: "/Applications/Discord.app/"
  pos: 7
- name: "Mission Control"
  path: "/Applications/Mission Control.app/"
  pos: 3
- name: "Obsidian"
  path: "/Applications/Obsidian.app/"
  pos: 6
- name: "Postman"
  path: "/Applications/Postman.app/"
  pos: 10
- name: "Spotify"
  path: "/Applications/Spotify.app/"
  pos: 8
- name: "Visual Studio Code"
  path: "/Applications/Visual Studio Code.app/"
  pos: 11

#-------------- Role: geerlingguy.dotfiles --------------#
# https://github.com/geerlingguy/ansible-role-dotfiles
configure_dotfiles: true

dotfiles_repo: https://github.com/BenWolfaardt/Dotfiles.git
dotfiles_repo_version: main
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/src/config/dotfiles
dotfiles_home: "~"
dotfiles_files:
  - .gitconfig
  - .gitignore
  - .p10k.zsh
  # - .osx
  - .zshenv
  - .zshprofile  # TODO: setup custom branches per OS
  - .zshrc

#-------------- Role: Settings --------------#
# Dock
dock_make_hidden_apps_translucent: true
dock_tilesize: 40

# Hostname
computername: Ben's-Hackintosh
hostname: null

# SSH
configure_ssh: false
# TODO figure out
ssh_keys:
  - name: "GitHub"
    host: "*.github.com"
    type: "ed25519"
    comment: "GitHub SSH"
  # - name: "gitlab"
  #   host: "gitlab.com"
  #   hostname: "username.gitlab.com"
  #   type: "rsa"
  #   comment: "some comment"

# System
system_save_application_state_on_quit: true
system_warn_before_emptying_the_trash: true

#-------------- Role: VSCode --------------#
vscode_extensions:
  - davidanson.vscode-markdownlint  # markdown lint
  - dbaeumer.vscode-eslint  # es lint
  - equinusocio.vsc-material-theme-icons  # material icon theme
  # - github.vscode-github-actions  # github actions
  - golang.go  # go
  - hashicorp.terraform  # terraform
  - juanblanco.solidity  # solidity
  # - johnpapa.vscode-peacock  # peacock - add colours to your windows
  - littlefoxteam.vscode-python-test-adapter  # python test explorer
  - mhutchie.git-graph  # git graph
  - ms-azuretools.vscode-docker  # docker
  - ms-vscode.live-server  # live html previewer
  - ms-python.debugpy # python debugger
  - ms-python.python  # python
  - ms-python.vscode-pylance  # pylance
  # - ms-vscode.makefile-tools  # Makefile Tools
  # - peterj.proto  # proto
  # - rust-lang.rust-analyzer  # rust
  - tamasfe.even-better-toml  # toml linting
  - tomoki1207.pdf  # pdf viewer
  # - yoavbls.pretty-ts-errors  # pretty ts errors
  - zxh404.vscode-proto3  # proto3

#-------------- Role: ignite --------------#
ignite_version: "v0.27.2"
