---
- name: Configure macOS
  
  hosts: localhost
  
  vars_files:
    - defaults.config.yml

  roles:
    # - role: geerlingguy.mac.homebrew
    #   tags: ["homebrew"]
    # - role: geerlingguy.mac.dock
    #   when: configure_dock
    #   tags: ['dock']
    # TODO figure out SSH things
    # - role: settings
    #   tags: [settings]
    # - role: maintenance
    #   tags: ["maintenance"]
    # Oh-my-zsh
    # Has to happen before dotfiles configuration or else it will overwrite
    # TODO Geerlingguy has a terminal config: https://github.com/geerlingguy/mac-dev-playbook/blob/master/tasks/terminal.yml
    # - role: shell
    #   tags: [shell]
    # - role: geerlingguy.dotfiles
    #   when: configure_dotfiles
    #   tags: ['dotfiles']
    # TODO test - having issues on Hackintosh
    # - role: docker
    #   tags: [docker]
    # - role: vscode
    #   tags: [vscode]
    # TODO fix, don't want to delete where I am currently working
    # - role: projects
    #   tags: [projects]