---
- name: Configure macOS
  hosts: localhost

  vars_files:
    - defaults.config.yml

  pre_tasks:
    - name: "Verifying playbook requirements"
      tags: ["always"]
      block:
        # TODO: Confirm version requirements?
        - name: Verify Ansible version.
          assert:
            that: "ansible_version.full is version_compare('2.13.0', '>=')"
            msg: "You must update Ansible to at least 2.13.0 to use this version of macOS-ansible."
        - name: Verify target system is running macOS.
          assert:
            that: "ansible_distribution == 'MacOSX'"
            msg: "The target system is not running macOS."
        # TODO: Confirm version requirements?
        - name: Verify macOS version.
          assert:
            that: "ansible_distribution_version is version_compare('12', '>=')"
            msg: "The target system must be running macOS 12 (Monterey) or higher to use this version of macOS-ansible."
    # - name: Include playbook configuration.
    #   include_vars: "{{ item }}"
    #   with_fileglob:
    #     - "{{ playbook_dir }}/config.yml"
    #   tags: ["always"]

  roles:
    # ------- default system ------- #
    # NOTE: Needs to happen before dotfiles have been installed
    # NOTE: Update aliases for Mac
    # - role: zsh  # working
    #   tags: ["zsh"]
    # - role: geerlingguy.dotfiles  # working
    #   when: configure_dotfiles
    #   tags: ['dotfiles']
    # - role: geerlingguy.mac.homebrew  # working
    #   tags: ["homebrew"]
    # - role: geerlingguy.mac.dock  # working
    #   when: configure_dock
    #   tags: ['dock']

    # ------- working ------- #

    # - role: foundry  # working
    #   tags: [foundry]
    # - role: go  # working
    #   tags: [go]
    # - role: ignite  # working
    #   tags: [ignite]
    # - role: java  # working
    #   tags: [java]
    # - role: nvm  # NVM and Node.js setup
    #   tags: [nvm]
    # - role: stretchly  # working
    #   tags: [stretchly]
    # - role: vscode  # working
    #   tags: [vscode]

# ------- Above is used --------- #

    # TODO: 1password
    #   GPG/SSH key for verifying
    # - role: ssh
    #   tags: [ssh]
    # - role: settings
    #   tags: [settings]
    # - role: maintenance
    #   tags: ["maintenance"]
    # Oh-my-zsh
    # Has to happen before dotfiles configuration or else it will overwrite
    # TODO Geerlingguy has a terminal config: https://github.com/geerlingguy/mac-dev-playbook/blob/master/tasks/terminal.yml
    # - role: shell
    #   tags: [shell]

    # TODO test - having issues on Hackintosh
    # - role: docker
    #   tags: [docker]

    # TODO fix, don't want to delete where I am currently working
    # - role: projects
    #   tags: [projects]

    # NOTE: WIP: Needs to happen after brew from geerlingguy has been installed
    # - role: wezterm
    #   tags: ["wezterm"]