---
- name: Install Visual Studio Code extensions
  command: code --install-extension {{ item }}
  with_items: '{{ vscode_extensions }}'
  ignore_errors: yes

# Should src be a different name?
- name: Create or update VSCode settings.json
  template:
    src: settings.json 
    dest: "{{ ansible_env.HOME }}/Library/Application Support/Code/User/settings.json"
