---
# Others:
#   https://github.com/gperdomor/macOS-ansible/blob/main/roles/settings/tasks/ssh.yml
#   https://github.com/adamchainz/mac-ansible/blob/main/roles/adam_mac/tasks/basic_settings.yml
#   https://github.com/ALT-F4-LLC/dotfiles/blob/main/roles/ssh/tasks/main.yaml
#     https://github.com/BenWolfaardt/dotfiles/blob/main/bin/dotfiles#L14
#     https://github.com/BenWolfaardt/dotfiles/blob/main/bin/dotfiles#L14

- name: ssh dir stat
  stat:
    path: ~/.ssh
  register: ssh_dir

- name: ssh dir exists
  when: not ssh_dir.stat.exists
  file:
    path: ~/.ssh
    state: directory

- name: ssh known_hosts contains github.com key
  lineinfile:
    dest: ~/.ssh/known_hosts
    create: true
    mode: 0644
    state: present
    line: "{{ lookup('file', 'github_ssh_host_key') }}"
    regexp: "^github\\.com "

